'use strict';
const items=window.NFT_CATALOG;
const grid=document.querySelector('#grid'), search=document.querySelector('#search'),dialog=document.querySelector('#detail');
let filter='all',lastTrigger;
const format=n=>n.toLocaleString('en-US');
function preview(item,trigger){lastTrigger=trigger;document.querySelector('#detail-title').textContent=item.title;document.querySelector('#detail-description').textContent=item.description;document.querySelector('#detail-category').textContent=item.saleCategory==='winner'?'FIRST-PLACE CONTEST WINNER':'SPECIAL COLLECTION';const image=document.querySelector('#detail-image');image.src=item.image;image.alt=item.alt;document.querySelector('#detail-price').textContent=format(item.burnAmount)+' SPARKD';document.querySelector('#detail-explorer').href=item.explorer;dialog.showModal();}
function render(){grid.replaceChildren();const query=search.value.trim().toLowerCase();const visible=items.filter(i=>(filter==='all'||i.saleCategory===filter)&&(i.title+' '+i.description).toLowerCase().includes(query));document.querySelector('#results').textContent=visible.length+' collectible'+(visible.length===1?'':'s')+' shown';document.querySelector('#empty').hidden=visible.length!==0;document.querySelector('#empty-title').textContent=query?'No matching artwork.':'The next winner belongs here.';document.querySelector('#empty-copy').textContent=query?'Try a different title or browse the full collection.':'First-place contest NFTs will appear here once their artwork is selected and minted.';for(const item of visible){const card=document.createElement('article');card.className='card';const art=document.createElement('div');art.className='card-art';const image=document.createElement('img');image.src=item.image;image.alt=item.alt;image.loading='lazy';image.width=600;image.height=600;const edition=document.createElement('span');edition.className='edition';edition.textContent='1 OF 1 · MINTED';art.append(image,edition);const body=document.createElement('div');body.className='card-body';const label=document.createElement('p');label.className='eyebrow';label.textContent=item.saleCategory==='winner'?'CONTEST WINNER':'SPECIAL COLLECTION';const title=document.createElement('h3');title.textContent=item.title.replace('SPARKD - ','');const bottom=document.createElement('div');bottom.className='card-bottom';const price=document.createElement('div');price.className='card-price';const amount=document.createElement('strong');amount.textContent=format(item.burnAmount)+' SPARKD';const note=document.createElement('span');note.textContent='PLANNED BURN PRICE';price.append(amount,note);const button=document.createElement('button');button.className='secondary';button.textContent='View artwork ↗';button.setAttribute('aria-label','View artwork: '+item.title);button.addEventListener('click',()=>preview(item,button));bottom.append(price,button);body.append(label,title,bottom);card.append(art,body);grid.append(card);}}
function setFilter(value){filter=value;document.querySelectorAll('[data-filter]').forEach(button=>{const selected=button.dataset.filter===filter;button.classList.toggle('active',selected);button.setAttribute('aria-pressed',String(selected));});render();}
document.querySelectorAll('[data-filter]').forEach(button=>button.addEventListener('click',()=>setFilter(button.dataset.filter)));search.addEventListener('input',render);document.querySelector('#reset').addEventListener('click',()=>{search.value='';setFilter('all');});document.querySelector('.close').addEventListener('click',()=>dialog.close());dialog.addEventListener('close',()=>lastTrigger?.focus());dialog.addEventListener('click',event=>{if(event.target===dialog){const r=dialog.getBoundingClientRect();if(event.clientX<r.left||event.clientX>r.right||event.clientY<r.top||event.clientY>r.bottom)dialog.close();}});render();
