window.NFT_CATALOG = [
  {
    "id": "first-spark",
    "title": "The First Spark",
    "category": "heroes",
    "label": "Heroes",
    "image": "assets/first-spark.png",
    "alt": "The First Spark: SPARKD Man powers up over a nighttime city",
    "style": "hero",
    "status": "minted",
    "assetAddress": "6WGq2FpB9DCW62by7VGbfSsRyYB6Zg6GixbnfT862zYj",
    "explorer": "https://core.metaplex.com/explorer/6WGq2FpB9DCW62by7VGbfSsRyYB6Zg6GixbnfT862zYj?env=mainnet",
    "collectionExplorer": "https://core.metaplex.com/explorer/collection/4ARoTdtbC6LzCQ4c8Fk4ZvmheQYE5vAnU5T6Mx3rs5A4?env=mainnet",
    "description": "SPARKD Man powers up above a nighttime city, surrounded by emerald energy and golden sparks. The first minted artwork in SPARKD Creative Art on Solana mainnet. Created with AI assistance.",
    "saleCategory": "special",
    "burnAmount": 30000
  },
  {
    "id": "secret-identity",
    "title": "The Secret Identity",
    "category": "origins",
    "label": "Origins",
    "image": "assets/secret-identity.png",
    "alt": "SPARKD’s mustached janitor identity holding his mop, wearing glasses and a purple-gray work shirt",
    "style": "origin",
    "status": "minted",
    "assetAddress": "2LhUSq81EFD4cq8Ed8EnqbaKg1futsr3mW1WwmfohyDG",
    "explorer": "https://core.metaplex.com/explorer/2LhUSq81EFD4cq8Ed8EnqbaKg1futsr3mW1WwmfohyDG?env=mainnet",
    "collectionExplorer": "https://core.metaplex.com/explorer/collection/4ARoTdtbC6LzCQ4c8Fk4ZvmheQYE5vAnU5T6Mx3rs5A4?env=mainnet",
    "description": "Behind the green cape is an ordinary janitor. SPARKD’s secret identity holds his mop, with tousled blond hair, glasses, a mustache, and his SPARKD work shirt. The second minted artwork in SPARKD Creative Art on Solana mainnet, issued as a 1-of-1 under our collection policy. Created with AI assistance.",
    "saleCategory": "special",
    "burnAmount": 30000
  },
  {
    "id": "ready-for-takeoff",
    "title": "Ready for Takeoff",
    "category": "community",
    "label": "Community",
    "image": "assets/ready-for-takeoff.jpg",
    "alt": "Black-and-green SPARKD jet at an airport at sunset",
    "style": "aviation",
    "status": "minted",
    "assetAddress": "8YKaY1srJoxvCnfrQ34Cp9LkTTRJiZC12tB4KqPGxH4F",
    "explorer": "https://core.metaplex.com/explorer/8YKaY1srJoxvCnfrQ34Cp9LkTTRJiZC12tB4KqPGxH4F?env=mainnet",
    "collectionExplorer": "https://core.metaplex.com/explorer/collection/4ARoTdtbC6LzCQ4c8Fk4ZvmheQYE5vAnU5T6Mx3rs5A4?env=mainnet",
    "description": "A SPARKD jet carries the community’s green loops and Ignite Real-World Good message into a golden airport sunset. The third minted artwork in SPARKD Creative Art on Solana mainnet, issued as a 1-of-1 under our collection policy.",
    "saleCategory": "special",
    "burnAmount": 30000
  },
  {
    "id": "heroes-dont-look-away",
    "title": "Heroes Don’t Look Away",
    "category": "heroes",
    "label": "Heroes",
    "image": "assets/heroes-dont-look-away.png",
    "alt": "SPARKD Man stops a semi-truck to protect a kitten on a wet road",
    "style": "rescue",
    "status": "minted",
    "description": "SPARKD Man stops a semi-truck to protect a tiny kitten. The fourth artwork in SPARKD Creative Art, minted on Solana mainnet. Created with AI assistance.",
    "assetAddress": "A3NNSJtfqdhKxDZopCmxErxppFGpakE5AVZSNmN2d1rn",
    "explorer": "https://core.metaplex.com/explorer/A3NNSJtfqdhKxDZopCmxErxppFGpakE5AVZSNmN2d1rn?env=mainnet",
    "collectionExplorer": "https://core.metaplex.com/explorer/collection/4ARoTdtbC6LzCQ4c8Fk4ZvmheQYE5vAnU5T6Mx3rs5A4?env=mainnet",
    "saleCategory": "special",
    "burnAmount": 30000
  },
  {
    "id": "justice-for-tomorrow",
    "title": "Justice for Tomorrow",
    "category": "heroes",
    "label": "Heroes",
    "image": "assets/justice-for-tomorrow.jpg",
    "alt": "SPARKD Man escorts a handcuffed fictional rug puller toward a jail",
    "style": "rescue",
    "status": "minted",
    "description": "SPARKD Man holds a fictional rug puller accountable in a scene of justice, cleaner communities, and brighter tomorrows. The fifth artwork in SPARKD Creative Art, minted on Solana mainnet. Created with AI assistance.",
    "assetAddress": "9V1E13fQqrRHobQi1ezpPLLQ5ktRuEkx1u246727UfDq",
    "explorer": "https://core.metaplex.com/explorer/9V1E13fQqrRHobQi1ezpPLLQ5ktRuEkx1u246727UfDq?env=mainnet",
    "collectionExplorer": "https://core.metaplex.com/explorer/collection/4ARoTdtbC6LzCQ4c8Fk4ZvmheQYE5vAnU5T6Mx3rs5A4?env=mainnet",
    "saleCategory": "special",
    "burnAmount": 30000
  },
  {
    "id": "chasing-the-jeets",
    "title": "SPARKD - Chasing the Jeets",
    "category": "heroes",
    "label": "Heroes",
    "image": "assets/chasing-the-jeets.jpg",
    "alt": "SPARKD man races through a neon-green metropolis in pursuit of a bear wearing a JEETS hoodie. A cinematic celebration of determination and the SPARKD community.",
    "style": "hero",
    "status": "minted",
    "assetAddress": "QTMZGvehRpBAQjs6uFMyqbJCEdhNhdCihXhRPBEk6D9",
    "explorer": "https://core.metaplex.com/explorer/QTMZGvehRpBAQjs6uFMyqbJCEdhNhdCihXhRPBEk6D9?env=mainnet",
    "collectionExplorer": "https://core.metaplex.com/explorer/collection/4ARoTdtbC6LzCQ4c8Fk4ZvmheQYE5vAnU5T6Mx3rs5A4?env=mainnet",
    "description": "SPARKD man races through a neon-green metropolis in pursuit of a bear wearing a JEETS hoodie. A cinematic celebration of determination and the SPARKD community.",
    "saleCategory": "special",
    "burnAmount": 30000
  },
  {
    "id": "the-rise-of-sparkd",
    "title": "The Rise of SPARKD",
    "category": "community",
    "label": "Community",
    "image": "assets/the-rise-of-sparkd.jpg",
    "alt": "SPARKD man sits with two allies at an ornate green-and-gold council table. The Rise of SPARKD celebrates community, ideas, technology, and a shared vision.",
    "style": "hero",
    "status": "minted",
    "assetAddress": "7frr8Pn7hUtzaSDSypc5eUYCKP632Drz58UahWfXWAWy",
    "explorer": "https://core.metaplex.com/explorer/7frr8Pn7hUtzaSDSypc5eUYCKP632Drz58UahWfXWAWy?env=mainnet",
    "collectionExplorer": "https://core.metaplex.com/explorer/collection/4ARoTdtbC6LzCQ4c8Fk4ZvmheQYE5vAnU5T6Mx3rs5A4?env=mainnet",
    "description": "SPARKD man sits with two allies at an ornate green-and-gold council table. The Rise of SPARKD celebrates community, ideas, technology, and a shared vision.",
    "saleCategory": "special",
    "burnAmount": 30000
  },
  {
    "id": "you-are-different",
    "title": "SPARKD - You Are Different",
    "category": "community",
    "label": "Community",
    "image": "assets/you-are-different.jpg",
    "alt": "A smiling stick figure embraces a companion with the SPARKD logo for a face beneath the words You’re different I like you. A simple meme celebrating individuality and connection.",
    "style": "community",
    "status": "minted",
    "assetAddress": "27oW4rNe4aDhjAeMCW8HbR32PjDvSAhJh9kmTCfRU8Ve",
    "explorer": "https://core.metaplex.com/explorer/27oW4rNe4aDhjAeMCW8HbR32PjDvSAhJh9kmTCfRU8Ve?env=mainnet",
    "collectionExplorer": "https://core.metaplex.com/explorer/collection/4ARoTdtbC6LzCQ4c8Fk4ZvmheQYE5vAnU5T6Mx3rs5A4?env=mainnet",
    "description": "A smiling stick figure embraces a companion with the SPARKD logo for a face beneath the words You’re different I like you. A simple meme celebrating individuality and connection.",
    "saleCategory": "special",
    "burnAmount": 30000
  },
  {
    "id": "bear-knockout",
    "title": "SPARKD - Bear Knockout",
    "category": "heroes",
    "label": "Heroes",
    "image": "assets/bear-knockout.jpg",
    "alt": "SPARKD man lands a golden-gloved punch against a boxing bear amid a vivid red-and-yellow comic burst. A playful superhero showdown with bold comic energy.",
    "style": "hero",
    "status": "minted",
    "assetAddress": "4Z1eNUv5WbKPVeVatPYuAej7NbYA71ezs8F4jgunGUhm",
    "explorer": "https://core.metaplex.com/explorer/4Z1eNUv5WbKPVeVatPYuAej7NbYA71ezs8F4jgunGUhm?env=mainnet",
    "collectionExplorer": "https://core.metaplex.com/explorer/collection/4ARoTdtbC6LzCQ4c8Fk4ZvmheQYE5vAnU5T6Mx3rs5A4?env=mainnet",
    "description": "SPARKD man lands a golden-gloved punch against a boxing bear amid a vivid red-and-yellow comic burst. A playful superhero showdown with bold comic energy.",
    "saleCategory": "special",
    "burnAmount": 30000
  }
];
