/* Three verified mainnet NFTs, two approved artworks awaiting mint, and one reference concept. */
window.SPARKD_NFT_CONCEPTS = [
  { id: 'first-spark', title: 'The First Spark', category: 'heroes', label: 'Heroes', image: 'assets/first-spark.png', alt: 'The First Spark: SPARKD Man powers up over a nighttime city', style: 'hero', status: 'minted', assetAddress: '6WGq2FpB9DCW62by7VGbfSsRyYB6Zg6GixbnfT862zYj', explorer: 'https://core.metaplex.com/explorer/6WGq2FpB9DCW62by7VGbfSsRyYB6Zg6GixbnfT862zYj?env=mainnet', collectionExplorer: 'https://core.metaplex.com/explorer/collection/4ARoTdtbC6LzCQ4c8Fk4ZvmheQYE5vAnU5T6Mx3rs5A4?env=mainnet', description: 'SPARKD Man powers up above a nighttime city, surrounded by emerald energy and golden sparks. The first minted artwork in SPARKD Creative Art on Solana mainnet. Created with AI assistance.' },
  { id: 'secret-identity', title: 'The Secret Identity', category: 'origins', label: 'Origins', image: 'assets/secret-identity.png', alt: 'SPARKD’s mustached janitor identity holding his mop, wearing glasses and a purple-gray work shirt', style: 'origin', status: 'minted', assetAddress: '2LhUSq81EFD4cq8Ed8EnqbaKg1futsr3mW1WwmfohyDG', explorer: 'https://core.metaplex.com/explorer/2LhUSq81EFD4cq8Ed8EnqbaKg1futsr3mW1WwmfohyDG?env=mainnet', collectionExplorer: 'https://core.metaplex.com/explorer/collection/4ARoTdtbC6LzCQ4c8Fk4ZvmheQYE5vAnU5T6Mx3rs5A4?env=mainnet', description: 'Behind the green cape is an ordinary janitor. SPARKD’s secret identity holds his mop, with tousled blond hair, glasses, a mustache, and his SPARKD work shirt. The second minted artwork in SPARKD Creative Art on Solana mainnet, issued as a 1-of-1 under our collection policy. Created with AI assistance.' },
  {"id":"ready-for-takeoff","title":"Ready for Takeoff","category":"community","label":"Community","image":"assets/ready-for-takeoff.jpg","alt":"Black-and-green SPARKD jet at an airport at sunset","style":"aviation","status":"minted","assetAddress":"8YKaY1srJoxvCnfrQ34Cp9LkTTRJiZC12tB4KqPGxH4F","explorer":"https://core.metaplex.com/explorer/8YKaY1srJoxvCnfrQ34Cp9LkTTRJiZC12tB4KqPGxH4F?env=mainnet","collectionExplorer":"https://core.metaplex.com/explorer/collection/4ARoTdtbC6LzCQ4c8Fk4ZvmheQYE5vAnU5T6Mx3rs5A4?env=mainnet","description":"A SPARKD jet carries the community’s green loops and Ignite Real-World Good message into a golden airport sunset. The third minted artwork in SPARKD Creative Art on Solana mainnet, issued as a 1-of-1 under our collection policy."},
  {"id":"heroes-dont-look-away","title":"Heroes Don’t Look Away","category":"heroes","label":"Heroes","image":"assets/heroes-dont-look-away.png","alt":"SPARKD Man stops a semi-truck to protect a kitten on a wet road","style":"rescue","status":"approved","description":"SPARKD Man stops a semi-truck to protect a tiny kitten. The fourth approved artwork in SPARKD Creative Art, with one NFT planned. Awaiting mint. Created with AI assistance."},
  {"id":"justice-for-tomorrow","title":"Justice for Tomorrow","category":"heroes","label":"Heroes","image":"assets/justice-for-tomorrow.jpg","alt":"SPARKD Man escorts a handcuffed fictional rug puller toward a jail","style":"rescue","status":"approved","description":"SPARKD Man holds a fictional rug puller accountable in a scene of justice, cleaner communities, and brighter tomorrows. The fifth approved artwork in SPARKD Creative Art, with one NFT planned. Awaiting mint. Created with AI assistance."},
  { id: 'community-spark', title: 'The Community Spark', category: 'community', label: 'Community', image: '../images/logo.png', alt: 'Official SPARKD logo reference', style: 'community', description: 'Inspired by the community that brings SPARKD to life. A planned collectible built around the official SPARKD loops, with a glowing green-and-gold composition. The image shown is the existing brand logo.' }
];
