import test from 'node:test';import assert from 'node:assert/strict';import {Buffer} from 'node:buffer';
import {Keypair,PublicKey,Transaction,SystemProgram} from '@solana/web3.js';
import {MAINNET,LISTINGS} from '../production-config.mjs';
import {ProductionCheckout,delegateFor,verifyQuote} from '../production-service.mjs';
import {validatePurchase,validateOwner} from '../client-validation.mjs';
const seed=Buffer.alloc(32,17);
function fixture(listed=true){const buyer=Keypair.generate(),store=new Map(),assets=LISTINGS.map(l=>({publicKey:l.asset,owner:MAINNET.seller,updateAuthority:{type:'Collection',address:MAINNET.collection},...(listed?{transferDelegate:{authority:{type:'Address',address:delegateFor(seed,l.asset).publicKey.toBase58()}}}:{})}));const connection={simulateTransaction:async()=>({value:{err:null}}),getGenesisHash:async()=>MAINNET.genesis,getLatestBlockhash:async()=>({blockhash:Keypair.generate().publicKey.toBase58(),lastValidBlockHeight:100}),getSignatureStatuses:async()=>({value:[null]}),getBlockHeight:async()=>101};const service=new ProductionCheckout(seed,store,{connection,readAsset:async(address)=>assets.find(a=>a.publicKey===address),readAllAssets:async()=>assets,readCollection:async()=>({publicKey:MAINNET.collection}),readMint:async()=>({decimals:6,isInitialized:true}),readTokens:async()=>({owner:buyer.publicKey,mint:new PublicKey(MAINNET.mint),amount:100000n*10n**6n})});const cfg={...MAINNET,owner:MAINNET.seller,delegates:Object.fromEntries(LISTINGS.map(l=>[l.id,delegateFor(seed,l.asset).publicKey.toBase58()]))};return {service,buyer,store,assets,cfg};}
for(const category of ['winner','special'])test('mainnet '+category+' constructs and validates the exact atomic purchase',async()=>{const {service,buyer,cfg,store}=fixture();const l=LISTINGS.find(l=>l.category===category),quote=await service.prepare(l.id,buyer.publicKey.toBase58()),tx=Transaction.from(Buffer.from(quote.transaction,'base64')),item={id:l.id,assetAddress:l.asset,burnAmount:category==='winner'?20000:30000};assert.equal(tx.instructions.length,2);assert.equal(tx.instructions[0].data.readBigUInt64LE(1),BigInt(item.burnAmount)*10n**6n);await validatePurchase(tx,quote,item,buyer.publicKey,cfg);tx.partialSign(buyer);assert.doesNotThrow(()=>verifyQuote(tx,store.get(quote.quoteId)));tx.instructions[0].data.writeBigUInt64LE(1n,1);tx.partialSign(buyer,delegateFor(seed,l.asset));assert.throws(()=>verifyQuote(tx,store.get(quote.quoteId)),/changed/);await assert.rejects(validatePurchase(tx,quote,item,buyer.publicKey,cfg));});
test('per-NFT delegates are stable and isolated',()=>{assert.equal(delegateFor(seed,LISTINGS[0].asset).publicKey.toBase58(),delegateFor(seed,LISTINGS[0].asset).publicKey.toBase58());assert.notEqual(delegateFor(seed,LISTINGS[0].asset).publicKey.toBase58(),delegateFor(seed,LISTINGS[1].asset).publicKey.toBase58());});
test('unlisted NFT, unknown ID, owner purchase and wrong network fail before signing',async()=>{const{service,buyer}=fixture(false);await assert.rejects(service.prepare(LISTINGS[0].id,buyer.publicKey.toBase58()),/authorized/);await assert.rejects(service.prepare('free',buyer.publicKey.toBase58()),/Unknown/);await assert.rejects(service.prepare(LISTINGS[0].id,MAINNET.seller),/different wallet/);service.connection.getGenesisHash=async()=>'devnet';await assert.rejects(service.inventory(),/not Solana mainnet/);});
test('insufficient balance never saves or signs a purchase quote',async()=>{const{service,buyer,store}=fixture();service.readTokens=async()=>({owner:buyer.publicKey,mint:new PublicKey(MAINNET.mint),amount:1n});await assert.rejects(service.prepare(LISTINGS[0].id,buyer.publicKey.toBase58()),/Insufficient/);assert.equal(store.size,0);});
test('only the exact owner can prepare listing and withdrawal transactions',async()=>{const{service,buyer,cfg}=fixture(false);const l=LISTINGS[0],item={id:l.id,assetAddress:l.asset,burnAmount:30000};await assert.rejects(service.prepareAdmin(l.id,buyer.publicKey.toBase58(),'list'),/owner wallet/);const q=await service.prepareAdmin(l.id,MAINNET.seller,'list'),tx=Transaction.from(Buffer.from(q.transaction,'base64'));validateOwner(tx,q,item,new PublicKey(MAINNET.seller),cfg,'list');assert.equal(tx.instructions[0].data[0],2);assert.equal(tx.instructions.length,1);assert.equal(tx.signatures.length,1);assert.equal(tx.signatures[0].signature,null);tx.add(SystemProgram.transfer({fromPubkey:new PublicKey(MAINNET.seller),toPubkey:buyer.publicKey,lamports:1}));assert.throws(()=>validateOwner(tx,q,item,new PublicKey(MAINNET.seller),cfg,'list'));});
test('withdrawal contains only revocation of this NFT delegate',async()=>{const{service,cfg}=fixture();const l=LISTINGS[0],q=await service.prepareAdmin(l.id,MAINNET.seller,'withdraw'),tx=Transaction.from(Buffer.from(q.transaction,'base64'));validateOwner(tx,q,{id:l.id,assetAddress:l.asset,burnAmount:30000},new PublicKey(MAINNET.seller),cfg,'withdraw');assert.equal(tx.instructions[0].data[0],10);});
test('expired request with a missing transaction can be safely retried after finalized expiry',async()=>{const{service,buyer,store}=fixture();const l=LISTINGS[0],quote=await service.prepare(l.id,buyer.publicKey.toBase58());const tx=Transaction.from(Buffer.from(quote.transaction,'base64'));tx.partialSign(buyer);const bs58=(await import('bs58')).default,signature=bs58.encode(tx.signature);assert.equal((await service.status(signature,l.id,buyer.publicKey.toBase58(),'purchase',quote.quoteId)).status,'expired');});
test('inventory distinguishes owner approvals from sold assets',async()=>{const{service,assets}=fixture(false);assets[1].owner=Keypair.generate().publicKey.toBase58();const inventory=await service.inventory();assert.equal(inventory[0].state,'unlisted');assert.equal(inventory[1].state,'sold');assert.equal(inventory.filter(i=>i.burnAmount===20000).length,4);assert.equal(inventory.filter(i=>i.burnAmount===30000).length,5);});

test('failed on-chain simulation never exposes a purchase quote',async()=>{const{service,buyer,store}=fixture();service.connection.simulateTransaction=async()=>({value:{err:{InstructionError:[1,'InvalidArgument']}}});await assert.rejects(service.prepare(LISTINGS[0].id,buyer.publicKey.toBase58()),/simulation rejected/);assert.equal(store.size,0);});
