import test from 'node:test';import assert from 'node:assert/strict';import {Keypair,Transaction,VersionedTransaction,SystemProgram,ComputeBudgetProgram} from '@solana/web3.js';import {signExactTransaction} from '../wallet-signing.mjs';
function setup(two=false){const owner=Keypair.generate(),delegate=Keypair.generate();const tx=new Transaction({feePayer:owner.publicKey,recentBlockhash:Keypair.generate().publicKey.toBase58()}).add(SystemProgram.transfer({fromPubkey:two?delegate.publicKey:owner.publicKey,toPubkey:Keypair.generate().publicKey,lamports:1}));if(two)tx.partialSign(delegate);return{owner,delegate,tx,bytes:tx.serialize({requireAllSignatures:false})};}
test('passes a genuine legacy Transaction to Phantom and retains exact quoted bytes',async()=>{const{owner,tx,bytes}=setup();const result=await signExactTransaction({request:()=>{throw Error('must not use raw request');},signTransaction:async v=>{assert.ok(v instanceof Transaction);v.partialSign(owner);return v;}},bytes,owner.publicKey);assert.ok(Transaction.from(result.bytes).verifySignatures());assert.deepEqual(Transaction.from(result.bytes).serializeMessage(),tx.serializeMessage());});
test('preserves the original co-signature when Phantom returns only the wallet signature',async()=>{const{owner,bytes}=setup(true);const result=await signExactTransaction({signTransaction:async v=>{v.partialSign(owner);return{signatures:v.signatures.filter(s=>s.publicKey.equals(owner.publicKey))};}},bytes,owner.publicKey);assert.ok(Transaction.from(result.bytes).verifySignatures());});
test('does not depend on wallet response serialization or its account reconstruction',async()=>{const{owner,bytes}=setup();const result=await signExactTransaction({signTransaction:async v=>{v.partialSign(owner);return{signatures:v.signatures,serialize:()=>{throw Error('wallet reserialization must not be used');}};}},bytes,owner.publicKey);assert.ok(Transaction.from(result.bytes).verifySignatures());});
test('rejects a signature on altered instructions even if the wallet approves them',async()=>{const{owner,bytes}=setup();await assert.rejects(signExactTransaction({signTransaction:async v=>{v.add(ComputeBudgetProgram.setComputeUnitPrice({microLamports:100}));v.partialSign(owner);return v;}},bytes,owner.publicKey),/Approval was not submitted/);});
test('rejects a missing wallet signature or switched wallet before submission',async()=>{const{owner,bytes}=setup();await assert.rejects(signExactTransaction({signTransaction:async v=>v},bytes,owner.publicKey),/Approval was not submitted/);await assert.rejects(signExactTransaction({signTransaction:()=>{throw Error('must not prompt');}},bytes,Keypair.generate().publicKey),/does not match/);});
test('accepts versioned-shaped signature arrays for the same exact quote',async()=>{const{owner,bytes}=setup();const result=await signExactTransaction({signTransaction:async v=>{v.partialSign(owner);return VersionedTransaction.deserialize(v.serialize());}},bytes,owner.publicKey);assert.ok(Transaction.from(result.bytes).verifySignatures());});
test('normalizes mobile base58 signatures without accepting changed transaction details',async()=>{const{owner,bytes}=setup();const bs58=(await import('bs58')).default;const result=await signExactTransaction({signTransaction:async v=>{v.partialSign(owner);return{signatures:v.signatures.map(s=>({...s,signature:bs58.encode(s.signature)}))};}},bytes,owner.publicKey);assert.ok(Transaction.from(result.bytes).verifySignatures());});
test('diagnoses wallet-added fee instructions before submission',async()=>{const{owner,bytes}=setup();await assert.rejects(signExactTransaction({signTransaction:async v=>{v.add(ComputeBudgetProgram.setComputeUnitPrice({microLamports:100}));v.partialSign(owner);return v;}},bytes,owner.publicKey),/wallet added fee instructions/);});
