import {Connection,Keypair,Transaction,LAMPORTS_PER_SOL} from '@solana/web3.js';
import {createMint,getOrCreateAssociatedTokenAccount,mintTo} from '@solana/spl-token';
import {createUmi} from '@metaplex-foundation/umi-bundle-defaults';
import {keypairIdentity,generateSigner,publicKey} from '@metaplex-foundation/umi';
import {mplCore,createCollection,create,fetchAsset} from '@metaplex-foundation/mpl-core';
import {writeFile,readFile} from 'node:fs/promises';import {CheckoutService} from './service.mjs';
const rpc='https://api.devnet.solana.com',connection=new Connection(rpc,'confirmed');let owner,buyer,delegate;
try{const keys=JSON.parse(await readFile('fixture-keys.local.json','utf8'));[owner,buyer,delegate]=keys.map(k=>Keypair.fromSecretKey(Uint8Array.from(k)));}catch{[owner,buyer,delegate]=[Keypair.generate(),Keypair.generate(),Keypair.generate()];await writeFile('fixture-keys.local.json',JSON.stringify([owner,buyer,delegate].map(k=>Array.from(k.secretKey))),{mode:0o600});}
for(const w of [owner,buyer])if(await connection.getBalance(w.publicKey)<0.1*LAMPORTS_PER_SOL){const s=await connection.requestAirdrop(w.publicKey,LAMPORTS_PER_SOL);await connection.confirmTransaction(s,'confirmed');}
const umi=createUmi(rpc).use(mplCore());umi.use(keypairIdentity(umi.eddsa.createKeypairFromSecretKey(owner.secretKey)));const collection=generateSigner(umi);await createCollection(umi,{collection,name:'SPARKD DEVNET TEST',uri:'https://sparkdcoin.com/NFT/'}).sendAndConfirm(umi);
const mint=await createMint(connection,owner,owner.publicKey,null,6);const ata=await getOrCreateAssociatedTokenAccount(connection,owner,mint,buyer.publicKey);await mintTo(connection,owner,mint,ata.address,owner,100000n*1000000n);const listings=[];
for(const category of ['winner','special']){const asset=generateSigner(umi);await create(umi,{asset,collection:collection.publicKey,name:'DEVNET ONLY '+category,uri:'https://sparkdcoin.com/NFT/',plugins:[{type:'TransferDelegate',authority:{type:'Address',address:publicKey(delegate.publicKey.toBase58())}}]}).sendAndConfirm(umi);listings.push({id:category,category,asset:asset.publicKey,seller:owner.publicKey.toBase58()});}
const config={cluster:'devnet',rpc,mint:mint.toBase58(),collection:collection.publicKey,delegateSecret:Array.from(delegate.secretKey),allowedOrigin:'http://localhost:8080',listings};await writeFile('test-config.local.json',JSON.stringify(config,null,2),{mode:0o600});
const service=new CheckoutService(config);for(const l of listings){const quote=await service.prepare(l.id,buyer.publicKey.toBase58());const tx=Transaction.from(Buffer.from(quote.transaction,'base64'));tx.partialSign(buyer);const result=await service.submit(quote.quoteId,tx.serialize().toString('base64'));if((await fetchAsset(umi,publicKey(l.asset))).owner!==buyer.publicKey.toBase58())throw Error('Wrong owner');console.log(JSON.stringify({category:l.category,burnAmount:quote.burnAmount,result}));}console.log('Both devnet purchases confirmed.');
