import {createHash,createHmac,randomUUID} from 'node:crypto';
import {Buffer} from 'node:buffer';
import {Connection,PublicKey,Keypair,Transaction,VersionedTransaction} from '@solana/web3.js';
import {getMint,getAccount,getAssociatedTokenAddress,createBurnCheckedInstruction,TOKEN_2022_PROGRAM_ID} from '@solana/spl-token';
import {createUmi} from '@metaplex-foundation/umi-bundle-defaults';
import {mplCore,fetchAsset,fetchAllAssets,fetchCollection,transfer,addPlugin,approvePluginAuthority,revokePluginAuthority} from '@metaplex-foundation/mpl-core';
import {publicKey,createNoopSigner} from '@metaplex-foundation/umi';
import {toWeb3JsInstruction} from '@metaplex-foundation/umi-web3js-adapters';
import bs58 from 'bs58';
import {amountFor,assertListing} from './service.mjs';
import {feeInstructions,coreInstructions} from './fee-policy.mjs';
import {MAINNET,LISTINGS} from './production-config.mjs';
const messageHash=tx=>createHash('sha256').update(tx.serializeMessage()).digest('hex');
export function delegateFor(seed,asset){return Keypair.fromSeed(createHmac('sha256',seed).update('SPARKD NFT Vault v1/mainnet/'+asset).digest());}
export function verifyQuote(tx,quote){if(messageHash(tx)!==quote.hash||!tx.verifySignatures())throw Error('Transaction details or wallet signatures changed');}
export class ProductionCheckout{
 constructor(seed,store,adapters={}){
  if(seed.length!==32)throw Error('Invalid signing seed');this.seed=seed;this.store=store;
  const rpc=adapters.rpc||'https://api.mainnet-beta.solana.com';
  this.connection=adapters.connection||new Connection(rpc,'confirmed');
  this.umi=createUmi(rpc).use(mplCore());
  this.readAsset=adapters.readAsset||((address)=>fetchAsset(this.umi,publicKey(address)));
  this.readAllAssets=adapters.readAllAssets||(()=>fetchAllAssets(this.umi,LISTINGS.map(l=>publicKey(l.asset))));
  this.readCollection=adapters.readCollection||(()=>fetchCollection(this.umi,publicKey(MAINNET.collection)));
  this.readMint=adapters.readMint||(()=>getMint(this.connection,new PublicKey(MAINNET.mint),'confirmed',TOKEN_2022_PROGRAM_ID));
  this.readTokens=adapters.readTokens||((ata)=>getAccount(this.connection,ata,'confirmed',TOKEN_2022_PROGRAM_ID));
 }
 async assertNetwork(){if(await this.connection.getGenesisHash()!==MAINNET.genesis)throw Error('Checkout RPC is not Solana mainnet');}
 listing(id){const l=LISTINGS.find(l=>l.id===id);if(!l)throw Error('Unknown NFT');return l;}
 async inspect(l,existing){const asset=existing||await this.readAsset(l.asset);if(asset.owner!==MAINNET.seller)throw Error('NFT is no longer available from the vault');if(asset.updateAuthority.type!=='Collection'||asset.updateAuthority.address!==MAINNET.collection)throw Error('Wrong NFT collection');if(asset.freezeDelegate?.frozen||asset.permanentFreezeDelegate?.frozen)throw Error('NFT is frozen');if(asset.permanentTransferDelegate||asset.oracle?.length||asset.lifecycleHook?.length)throw Error('Unsupported NFT transfer rules');return asset;}
 async inventory(){await this.assertNetwork();const assets=await this.readAllAssets();return Promise.all(LISTINGS.map(async l=>{const delegate=delegateFor(this.seed,l.asset).publicKey.toBase58();try{const asset=assets.find(a=>a.publicKey===l.asset);if(!asset)throw Error("NFT account missing");if(asset.owner!==MAINNET.seller)return {...l,delegate,burnAmount:Number(amountFor(l,0)),state:'sold',available:false};await this.inspect(l,asset);const available=asset.transferDelegate?.authority?.type==='Address'&&asset.transferDelegate.authority.address===delegate;return {...l,delegate,burnAmount:Number(amountFor(l,0)),state:available?'available':'unlisted',available};}catch{return {...l,delegate,burnAmount:Number(amountFor(l,0)),state:'unavailable',available:false};}}));}
 async simulate(tx){const result=await this.connection.simulateTransaction(new VersionedTransaction(tx.compileMessage()),{sigVerify:false,commitment:'confirmed'});if(result.value.err)throw Error('Solana simulation rejected this transaction: '+JSON.stringify(result.value.err));}
 async save(tx,l,buyer,kind,extra={}){const quoteId=randomUUID(),expiresAt=Date.now()+90000;await this.store.set(quoteId,{hash:messageHash(tx),expires:expiresAt,listing:l,buyer,kind,...extra});return {quoteId,transaction:tx.serialize({requireAllSignatures:false}).toString('base64'),cluster:MAINNET.cluster,buyer,asset:l.asset,mint:MAINNET.mint,collection:MAINNET.collection,delegate:delegateFor(this.seed,l.asset).publicKey.toBase58(),burnAmount:Number(amountFor(l,0)),expiresAt,...extra};}
 async prepare(id,buyerAddress){await this.assertNetwork();const l=this.listing(id),buyer=new PublicKey(buyerAddress),delegate=delegateFor(this.seed,l.asset);if(buyer.toBase58()===MAINNET.seller||buyer.equals(delegate.publicKey))throw Error('Use a different wallet to purchase an NFT you own');const asset=await this.inspect(l);assertListing(asset,l,MAINNET.collection,delegate.publicKey.toBase58());const collection=await this.readCollection();const mint=await this.readMint();if(mint.isInitialized===false)throw Error('Token mint is not initialized');const amount=amountFor(l,mint.decimals),ata=await getAssociatedTokenAddress(new PublicKey(MAINNET.mint),buyer,false,TOKEN_2022_PROGRAM_ID);const tokens=await this.readTokens(ata);if(!tokens.owner.equals(buyer)||tokens.mint.toBase58()!==MAINNET.mint||tokens.amount<amount||tokens.isFrozen)throw Error('Insufficient spendable SPARKD balance');const latest=await this.connection.getLatestBlockhash('confirmed');const tx=new Transaction({feePayer:buyer,...latest});tx.add(createBurnCheckedInstruction(ata,new PublicKey(MAINNET.mint),buyer,amount,mint.decimals,[],TOKEN_2022_PROGRAM_ID));const builder=transfer(this.umi,{asset,collection,newOwner:publicKey(buyer.toBase58()),authority:createNoopSigner(publicKey(delegate.publicKey.toBase58())),payer:createNoopSigner(publicKey(buyer.toBase58()))});tx.add(...builder.getInstructions().map(toWeb3JsInstruction));if(tx.instructions.length!==2)throw Error('Unsupported NFT transaction');tx.instructions.unshift(...feeInstructions());await this.simulate(tx);tx.partialSign(delegate);return this.save(tx,l,buyer.toBase58(),'purchase',{decimals:mint.decimals,amount:amount.toString(),latest});}
 async prepareAdmin(id,ownerAddress,action){await this.assertNetwork();if(ownerAddress!==MAINNET.seller)throw Error('Connect the NFT owner wallet');if(!['list','withdraw'].includes(action))throw Error('Invalid owner action');const l=this.listing(id),asset=await this.inspect(l),delegate=delegateFor(this.seed,l.asset).publicKey.toBase58(),owner=createNoopSigner(publicKey(MAINNET.seller));const args={asset:publicKey(l.asset),collection:publicKey(MAINNET.collection),payer:owner,authority:owner};let builder;
  if(action==='withdraw'){if(asset.transferDelegate?.authority?.type!=='Address'||asset.transferDelegate.authority.address!==delegate)throw Error('This NFT is not listed with the vault');builder=revokePluginAuthority(this.umi,{...args,plugin:{type:'TransferDelegate'}});}
  else if(!asset.transferDelegate){builder=addPlugin(this.umi,{...args,plugin:{type:'TransferDelegate',authority:{type:'Address',address:publicKey(delegate)}}});}
  else {if(asset.transferDelegate.authority.type!=='Owner')throw Error('This NFT already has a transfer delegate; withdraw that delegation first');builder=approvePluginAuthority(this.umi,{...args,plugin:{type:'TransferDelegate'},newAuthority:{type:'Address',address:publicKey(delegate)}});}
  const latest=await this.connection.getLatestBlockhash('confirmed'),tx=new Transaction({feePayer:new PublicKey(MAINNET.seller),...latest});tx.add(...builder.getInstructions().map(toWeb3JsInstruction));tx.instructions.unshift(...feeInstructions());await this.simulate(tx);return this.save(tx,l,MAINNET.seller,action,{latest});
 }
 async submit(id,serialized){await this.assertNetwork();const quote=await this.store.get(id);if(!quote)throw Error('Purchase request not found');const tx=Transaction.from(Buffer.from(serialized,'base64'));verifyQuote(tx,quote);const signature=bs58.encode(tx.signature);quote.signature=signature;await this.store.set(id,quote);const existing=await this.connection.getSignatureStatuses([signature],{searchTransactionHistory:true});if(!existing.value[0]){if(quote.expires<Date.now())throw Error('Request expired. No transaction was submitted by this request.');await this.connection.sendRawTransaction(tx.serialize(),{skipPreflight:false,maxRetries:2});}return {...await this.status(signature,quote.listing.id,quote.buyer,quote.kind,id),signature};}
 async status(signature,id,buyer,kind='purchase',quoteId){await this.assertNetwork();if(!/^[1-9A-HJ-NP-Za-km-z]{80,90}$/.test(signature))throw Error('Invalid transaction signature');const l=this.listing(id),result=await this.connection.getSignatureStatuses([signature],{searchTransactionHistory:true}),status=result.value[0];if(!status){const quote=quoteId?await this.store.get(quoteId):null;if(quote&&quote.listing.id===id&&quote.buyer===buyer&&quote.kind===kind&&await this.connection.getBlockHeight('finalized')>quote.latest.lastValidBlockHeight)return {status:'expired',signature,error:'The transaction expired without confirmation. You can try again.'};return {status:'pending',signature};}if(status.err)return {status:'failed',signature,error:'Transaction failed. The burn and transfer were rolled back; network fees may still apply.'};if(!['confirmed','finalized'].includes(status.confirmationStatus))return {status:'pending',signature};const chainTx=await this.connection.getTransaction(signature,{commitment:'confirmed',maxSupportedTransactionVersion:0});if(!chainTx)return {status:'pending',signature};const message=chainTx.transaction.message;const accounts=message.accountKeys;const rawInstructions=message.instructions;const normalized=rawInstructions?.map(ix=>({programId:accounts[ix.programIdIndex],keys:ix.accounts.map(i=>({pubkey:accounts[i]})),data:Buffer.from(bs58.decode(ix.data))}));const count=normalized?coreInstructions(normalized).length:0;const instructions=rawInstructions?.slice(rawInstructions.length-count);const delegate=delegateFor(this.seed,l.asset).publicKey.toBase58();if(!accounts||!instructions||!accounts[0].equals(new PublicKey(buyer)))throw Error('Transaction does not match the requested wallet');const asset=await this.readAsset(l.asset);
  if(kind==='purchase'){if(instructions.length!==2||accounts[instructions[0].programIdIndex].toBase58()!==TOKEN_2022_PROGRAM_ID.toBase58()||accounts[instructions[1].programIdIndex].toBase58()!=='CoREENxT6tW1HoK8ypY1SxRMZTcVPm7R94rH4PZNhX7d')throw Error('Transaction is not a vault purchase');const burn=Buffer.from(bs58.decode(instructions[0].data));const mint=await this.readMint();if(burn.length!==10||burn[0]!==15||burn.readBigUInt64LE(1)!==amountFor(l,mint.decimals)||burn[9]!==mint.decimals||accounts[instructions[0].accounts[1]].toBase58()!==MAINNET.mint||accounts[instructions[1].accounts[0]].toBase58()!==l.asset||accounts[instructions[1].accounts[3]].toBase58()!==delegate||accounts[instructions[1].accounts[4]].toBase58()!==buyer)throw Error('Transaction does not match the NFT and price');if(asset.owner!==buyer)return {status:'pending',signature};}
  else {if(buyer!==MAINNET.seller||!['list','withdraw'].includes(kind))throw Error('Invalid owner request');const ix=instructions[0];if(instructions.length!==1||accounts[ix.programIdIndex].toBase58()!=='CoREENxT6tW1HoK8ypY1SxRMZTcVPm7R94rH4PZNhX7d'||accounts[ix.accounts[0]].toBase58()!==l.asset)throw Error('Transaction is not an owner listing');const listed=asset.transferDelegate?.authority?.type==='Address'&&asset.transferDelegate.authority.address===delegate;if(kind==='list'&&!listed||kind==='withdraw'&&listed)return {status:'pending',signature};}
  return {status:'confirmed',signature,asset:l.asset,owner:asset.owner,kind};
 }
}
