import {createHash,randomUUID} from 'node:crypto';
import {Connection,PublicKey,Keypair,Transaction,TransactionInstruction} from '@solana/web3.js';
import {getMint,getAccount,getAssociatedTokenAddress,createBurnCheckedInstruction,TOKEN_PROGRAM_ID} from '@solana/spl-token';
import {createUmi} from '@metaplex-foundation/umi-bundle-defaults';
import {mplCore,fetchAsset,fetchCollection,transfer} from '@metaplex-foundation/mpl-core';
import {publicKey,createNoopSigner} from '@metaplex-foundation/umi';
import {toWeb3JsInstruction} from '@metaplex-foundation/umi-web3js-adapters';
export const MAINNET_GENESIS='5eykt4UsFv8P8NJdTREpY1vzqKqZKvdp';
export const DEVNET_GENESIS='EtWTRABZaYq6iMfeYKouRu166VU2xqa1';
export function amountFor(listing,decimals){if(!Number.isInteger(decimals)||decimals<0||decimals>9)throw Error('Unsupported token precision');const prices={winner:20000,special:30000};if(!prices[listing.category])throw Error('Invalid category');return BigInt(prices[listing.category])*10n**BigInt(decimals);}
export function assertListing(asset,listing,collection,delegate){if(asset.owner!==listing.seller)throw Error('NFT is unavailable');if(asset.updateAuthority.type!=='Collection'||asset.updateAuthority.address!==collection)throw Error('Wrong collection');if(asset.transferDelegate?.authority?.type!=='Address'||asset.transferDelegate.authority.address!==delegate)throw Error('Listing has not been authorized');if(asset.freezeDelegate?.frozen||asset.permanentFreezeDelegate?.frozen)throw Error('NFT is frozen');}
const hash=tx=>createHash('sha256').update(tx.serializeMessage()).digest('hex');
export class CheckoutService{
 constructor(config,adapters={}){if(config.cluster!=='devnet')throw Error('This test build only permits devnet');if(!Array.isArray(config.listings)||!config.listings.length)throw Error('No test listings configured');if(config.mint==='BMU2rhUtANRS1hYKC1pQgxjcJ2Pn9PQURcf8CcRVpump')throw Error('Real SPARKD mint forbidden in devnet tests');this.config=config;this.delegate=Keypair.fromSecretKey(Uint8Array.from(config.delegateSecret));this.connection=adapters.connection||new Connection(config.rpc,'confirmed');this.umi=createUmi(config.rpc).use(mplCore());this.quotes=new Map();}
 async assertNetwork(){if(await this.connection.getGenesisHash()!==DEVNET_GENESIS)throw Error('RPC is not Solana devnet');}
 async prepare(id,buyerAddress){await this.assertNetwork();const listing=this.config.listings.find(x=>x.id===id);if(!listing)throw Error('Unknown listing');const buyer=new PublicKey(buyerAddress),mint=new PublicKey(this.config.mint);if(buyer.toBase58()===listing.seller||buyer.equals(this.delegate.publicKey))throw Error('Invalid buyer');const asset=await fetchAsset(this.umi,publicKey(listing.asset));assertListing(asset,listing,this.config.collection,this.delegate.publicKey.toBase58());const collection=await fetchCollection(this.umi,publicKey(this.config.collection));const mintInfo=await getMint(this.connection,mint,'confirmed',TOKEN_PROGRAM_ID);const amount=amountFor(listing,mintInfo.decimals);const ata=await getAssociatedTokenAddress(mint,buyer);const account=await getAccount(this.connection,ata,'confirmed',TOKEN_PROGRAM_ID);if(!account.owner.equals(buyer)||!account.mint.equals(mint)||account.amount<amount)throw Error('Insufficient test SPARKD balance');const latest=await this.connection.getLatestBlockhash('confirmed');const tx=new Transaction({feePayer:buyer,...latest});tx.add(createBurnCheckedInstruction(ata,mint,buyer,amount,mintInfo.decimals,[],TOKEN_PROGRAM_ID));const noop=createNoopSigner(publicKey(this.delegate.publicKey.toBase58()));const builder=transfer(this.umi,{asset,collection,newOwner:publicKey(buyer.toBase58()),authority:noop,payer:createNoopSigner(publicKey(buyer.toBase58()))});for(const ix of builder.getInstructions())tx.add(toWeb3JsInstruction(ix));tx.partialSign(this.delegate);const idQuote=randomUUID();for(const [k,v] of this.quotes)if(v.expires<Date.now())this.quotes.delete(k);if(this.quotes.size>=500)throw Error('Checkout busy');this.quotes.set(idQuote,{hash:hash(tx),expires:Date.now()+90000,latest,buyer:buyer.toBase58(),listing,signature:null});return {quoteId:idQuote,transaction:tx.serialize({requireAllSignatures:false}).toString('base64'),cluster:'devnet',buyer:buyer.toBase58(),mint:mint.toBase58(),amount:amount.toString(),decimals:mintInfo.decimals,burnAmount:Number(amount/10n**BigInt(mintInfo.decimals)),asset:listing.asset,delegate:this.delegate.publicKey.toBase58(),expiresAt:Date.now()+90000};}
 async submit(id,serialized){await this.assertNetwork();const quote=this.quotes.get(id);if(!quote||quote.expires<Date.now())throw Error('Quote expired; request a new quote');const tx=Transaction.from(Buffer.from(serialized,'base64'));if(hash(tx)!==quote.hash||!tx.verifySignatures())throw Error('Transaction or signatures changed');if(!quote.signature){quote.signature=await this.connection.sendRawTransaction(tx.serialize(),{skipPreflight:false,maxRetries:2});}const result=await this.connection.confirmTransaction({...quote.latest,signature:quote.signature},'confirmed');if(result.value.err)throw Error('Purchase failed; burn and transfer were rolled back. Network fees may still apply.');const asset=await fetchAsset(this.umi,publicKey(quote.listing.asset));if(asset.owner!==quote.buyer)throw Error('Confirmation pending; inspect transaction before retrying');return {signature:quote.signature,asset:quote.listing.asset,owner:quote.buyer,status:'confirmed',cluster:'devnet'};}
 async inventory(){await this.assertNetwork();return Promise.all(this.config.listings.map(async l=>{try{const a=await fetchAsset(this.umi,publicKey(l.asset));assertListing(a,l,this.config.collection,this.delegate.publicKey.toBase58());return {id:l.id,available:true,burnAmount:Number(amountFor(l,0)),asset:l.asset};}catch{return{id:l.id,available:false,asset:l.asset};}}));}
}
