import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';
import {Connection,PublicKey,Keypair,Transaction,VersionedTransaction} from '@solana/web3.js';
import {getAssociatedTokenAddress,createBurnCheckedInstruction,TOKEN_2022_PROGRAM_ID,MintLayout,AccountLayout} from '@solana/spl-token';
import {createUmi} from '@metaplex-foundation/umi-bundle-defaults';import {publicKey,createNoopSigner} from '@metaplex-foundation/umi';import {mplCore,addPlugin,transferV1,deserializeAssetV1} from '@metaplex-foundation/mpl-core';import {toWeb3JsInstruction} from '@metaplex-foundation/umi-web3js-adapters';import {MAINNET,LISTINGS} from './production-config.mjs';
const configText=await readFile('../checkout-config.js','utf8');const cfg=JSON.parse(configText.slice(configText.indexOf('(')+1,configText.lastIndexOf(')')));const inventory=Object.entries(cfg.delegates).map(([id,delegate])=>({id,delegate})),c=new Connection('https://api.mainnet-beta.solana.com','confirmed'),u=createUmi(c.rpcEndpoint).use(mplCore()),owner=new PublicKey(MAINNET.seller),mint=new PublicKey(MAINNET.mint),ata=await getAssociatedTokenAddress(mint,owner,false,TOKEN_2022_PROGRAM_ID),payer=createNoopSigner(publicKey(MAINNET.seller)),recipient=Keypair.generate().publicKey;
for(const category of ['winner','special']){
 const l=LISTINGS.find(l=>l.category===category),delegate=inventory.find(i=>i.id===l.id).delegate,amount=BigInt(category==='winner'?20000:30000)*10n**6n;
 const original=await c.getMultipleAccountsInfo([mint,ata,new PublicKey(l.asset)]);const baseMint=MintLayout.decode(original[0].data),baseToken=AccountLayout.decode(original[1].data);
 const tx=new Transaction({feePayer:owner,...await c.getLatestBlockhash('confirmed')});tx.add(...addPlugin(u,{asset:publicKey(l.asset),collection:publicKey(MAINNET.collection),authority:payer,payer,plugin:{type:'TransferDelegate',authority:{type:'Address',address:publicKey(delegate)}}}).getInstructions().map(toWeb3JsInstruction));
 tx.add(createBurnCheckedInstruction(ata,mint,owner,amount,6,[],TOKEN_2022_PROGRAM_ID));tx.add(...transferV1(u,{asset:publicKey(l.asset),collection:publicKey(MAINNET.collection),authority:createNoopSigner(publicKey(delegate)),payer,newOwner:publicKey(recipient.toBase58())}).getInstructions().map(toWeb3JsInstruction));
 const options={sigVerify:false,commitment:'confirmed',accounts:{encoding:'base64',addresses:[mint.toBase58(),ata.toBase58(),l.asset]}};
 const result=await c.simulateTransaction(new VersionedTransaction(tx.compileMessage()),options);if(result.value.err){console.log(category,'simulation failed',result.value.err,result.value.logs?.slice(-5));throw Error('Simulation failed');}
 const accounts=result.value.accounts.map(a=>Buffer.from(a.data[0],'base64'));assert.equal(MintLayout.decode(accounts[0]).supply,baseMint.supply-amount);assert.equal(AccountLayout.decode(accounts[1]).amount,baseToken.amount-amount);assert.equal(deserializeAssetV1({...await u.rpc.getAccount(publicKey(l.asset)),data:accounts[2]}).owner,recipient.toBase58());console.log(category,'mainnet simulation passed: exact burn and NFT transfer; no transaction sent');
 tx.instructions[2].keys[3].pubkey=Keypair.generate().publicKey;tx.recentBlockhash=(await c.getLatestBlockhash('confirmed')).blockhash;
 const rejected=await c.simulateTransaction(new VersionedTransaction(tx.compileMessage()),options);assert.ok(rejected.value.err);console.log(category,'wrong-delegate simulation correctly failed',JSON.stringify(rejected.value.err));
 const after=await c.getMultipleAccountsInfo([mint,ata,new PublicKey(l.asset)]);assert.deepEqual(after[2].data,original[2].data);assert.equal(AccountLayout.decode(after[1].data).amount,baseToken.amount);console.log(category,'real NFT ownership and owner token balance unchanged');
}
