(() => {
  "use strict";
  const VERSION="2.1",ROOT_ID="sparkdContestRules",MODAL_ID="sparkdContestRulesModal";
  const RULE_SECTIONS=[
    {title:"1. Contest Overview",items:["SPARKD Meme of the Week is a weekly meme contest.","Submissions open and close on the schedule shown on the live contest page.","After submissions close, eligible memes are selected by an automated equal-chance random drawing."]},
    {title:"2. Entry Requirements",items:["Entries must be submitted through the official SPARKD Meme of the Week submission system.","The meme must be a valid SPARKD Meme Forge PNG that passes Forge DNA verification.","The submitting wallet must hold at least 2,000 SPARKD when the entry is prepared, and entry requires a verified burn of exactly 2,000 SPARKD.","A meme title is required and the submission must be completed during the active submission window.","A rejected submission is not eligible for the drawing."]},
    {title:"3. Equal-Chance Drawing",items:["Every eligible meme receives exactly one drawing entry.","Each eligible meme has the same chance in the drawing.","The server cryptographically shuffles the frozen eligible submission list and selects up to three unique finalists.","Those finalists are shuffled again to assign 1st, 2nd, and 3rd place.","A single submission cannot occupy more than one prize position.","Once a draw is finalized, rerunning the lifecycle preserves the finalized winner record rather than intentionally selecting a new set of winners."]},
    {title:"4. Edge Cases",items:["With three or more eligible memes, three winners are selected.","With two eligible memes, only 1st and 2nd place are awarded.","With one eligible meme, that meme receives 1st place.","With zero eligible memes, no winner or meme prize payout is created and the contest proceeds to the next week."]},
    {title:"5. Draw Verification",items:["Each random drawing stores an audit record containing the eligible entry count, a commitment to the frozen entrant list, randomness information, finalist IDs, final placement order, draw timestamp, and algorithm identifier.","The contest page exposes completed random-draw audit information for public inspection."]},
    {title:"6. Prizes & Payouts",items:["First place receives $15 USD worth of SOL, second place receives $10 USD worth of SOL, and third place receives $5 USD worth of SOL.","The SOL amount is calculated from the USD prize value when payout is prepared.","Winner selection is finalized separately from payout execution. Automated payout jobs use the finalized winner records."]},
    {title:"7. Technical Authority",items:["Server and database time control contest deadlines and eligibility.","The database lifecycle runs automatically and is the authority for draw finalization and contest rollover.","Transactions or submissions that fail required verification are not eligible entries."]}
  ];
  function styles(){if(document.getElementById("sparkdContestRulesStyles"))return;const s=document.createElement("style");s.id="sparkdContestRulesStyles";s.textContent=`#${ROOT_ID}{display:inline-flex;align-items:center;gap:12px;flex-wrap:wrap}#${ROOT_ID} button{border:1px solid rgba(255,196,0,.55);background:#18181c;color:#fff;border-radius:999px;padding:9px 14px;font-weight:900;cursor:pointer}#${MODAL_ID}{position:fixed;inset:0;z-index:100000;display:none;align-items:center;justify-content:center;padding:22px;background:rgba(0,0,0,.76)}#${MODAL_ID}.open{display:flex}#${MODAL_ID} .panel{width:min(920px,100%);max-height:88vh;overflow:auto;background:#111116;color:#f5f5f7;border:1px solid rgba(255,255,255,.15);border-radius:22px;padding:20px}#${MODAL_ID} h2{margin-top:0}#${MODAL_ID} section{padding:14px 0;border-bottom:1px solid rgba(255,255,255,.09)}#${MODAL_ID} li{margin:8px 0;line-height:1.5}.sparkd-rules-close{float:right;width:40px;height:40px;border-radius:50%;background:#222;color:#fff;border:1px solid #555;font-size:22px;cursor:pointer}`;document.head.appendChild(s);}
  function modal(){if(document.getElementById(MODAL_ID))return;const m=document.createElement("div");m.id=MODAL_ID;m.innerHTML=`<div class="panel"><button class="sparkd-rules-close" aria-label="Close">×</button><h2>📜 SPARKD Contest Rules</h2><p>Official prizes are selected by an automated equal-chance random drawing.</p>${RULE_SECTIONS.map(x=>`<section><h3>${x.title}</h3><ul>${x.items.map(i=>`<li>${i}</li>`).join("")}</ul></section>`).join("")}</div>`;const close=()=>m.classList.remove("open");m.querySelector("button").onclick=close;m.onclick=e=>{if(e.target===m)close()};document.body.appendChild(m);}
  function inject(){if(document.getElementById(ROOT_ID))return true;const week=document.getElementById("winnerWeek");if(!week)return false;const wrap=document.createElement("div");wrap.id=ROOT_ID;week.parentNode.insertBefore(wrap,week);wrap.appendChild(week);const b=document.createElement("button");b.type="button";b.textContent="📜 CONTEST RULES";b.onclick=()=>document.getElementById(MODAL_ID)?.classList.add("open");wrap.appendChild(b);return true;}
  function start(){styles();modal();if(!inject()){let n=0,t=setInterval(()=>{if(inject()||++n>20)clearInterval(t)},250)}}
  if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",start,{once:true});else start();
  window.SPARKD_CONTEST_RULES={version:VERSION,rules:RULE_SECTIONS};
})();
